site_name: "🚀"
site_description: "Let's get acquainted"
site_author: "Daniil Startsev"
site_url: "https://Alator2001.github.io/my-personal-site/"

nav:
  - index.md
  - about.md
  - projects.md
  - contacts.md

theme:
  name: material
  language: en
  logo: images/logo.png
  font:
    text: Inter
    code: JetBrains Mono
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.sections
    - navigation.top
    - navigation.footer
    # - navigation.instant   # ← отключил, мешает переключателю языка
    - toc.follow
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.tabs.link
    - header.autohide
  palette:
    - scheme: slate
      primary: indigo
      accent: teal

plugins:
  - search:
      lang:
        - en
        - ru
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          name: English
          default: true
          build: true
        - locale: ru
          name: Русский
          build: true

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Alator2001
    - icon: fontawesome/brands/telegram
      link: https://t.me/ghulqul
  # абсолютные пути с завершающим слэшем (и локально, и на GH Pages ок)
  alternate:
    - name: English
      link: /my-personal-site/
      lang: en
    - name: Русский
      link: /devops-lab-startsev/ru/
      lang: ru

extra_css:
  - styles/overrides.css
  - styles/stars.css

extra_javascript:
  - scripts/stars.js
  - scripts/lang-toggle.js   # ← новый
